--- #YAML:1.0
name:               Imager
version:            0.71_02
abstract:           Perl extension for Generating 24 bit Images
author:
    - Tony Cook <tony@imager.perl.org>, Arnar M. Hrafnkelsson
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0.47
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
dynamic_config:     1
recommends:
    Parse::RecDescent:  0
