# AUTOMATICALLY GENERATED BY regops.perl
package Imager::Regops;
use strict;
require Exporter;
use vars qw(@ISA @EXPORT @EXPORT_OK %Attr $MaxOperands $PackCode);
@ISA = qw(Exporter);
@EXPORT_OK = qw(%Attr $MaxOperands $PackCode);

use constant RBC_ADD => 0;
use constant RBC_SUBTRACT => 1;
use constant RBC_MULT => 2;
use constant RBC_DIV => 3;
use constant RBC_MOD => 4;
use constant RBC_POW => 5;
use constant RBC_UMINUS => 6;
use constant RBC_MULTP => 7;
use constant RBC_ADDP => 8;
use constant RBC_SUBTRACTP => 9;
use constant RBC_SIN => 10;
use constant RBC_COS => 11;
use constant RBC_ATAN2 => 12;
use constant RBC_SQRT => 13;
use constant RBC_DISTANCE => 14;
use constant RBC_GETP1 => 15;
use constant RBC_GETP2 => 16;
use constant RBC_GETP3 => 17;
use constant RBC_VALUE => 18;
use constant RBC_HUE => 19;
use constant RBC_SAT => 20;
use constant RBC_HSV => 21;
use constant RBC_RED => 22;
use constant RBC_GREEN => 23;
use constant RBC_BLUE => 24;
use constant RBC_RGB => 25;
use constant RBC_INT => 26;
use constant RBC_IF => 27;
use constant RBC_IFP => 28;
use constant RBC_LE => 29;
use constant RBC_LT => 30;
use constant RBC_GE => 31;
use constant RBC_GT => 32;
use constant RBC_EQ => 33;
use constant RBC_NE => 34;
use constant RBC_AND => 35;
use constant RBC_OR => 36;
use constant RBC_NOT => 37;
use constant RBC_ABS => 38;
use constant RBC_RET => 39;
use constant RBC_JUMP => 40;
use constant RBC_JUMPZ => 41;
use constant RBC_JUMPNZ => 42;
use constant RBC_SET => 43;
use constant RBC_SETP => 44;
use constant RBC_PRINT => 45;
use constant RBC_RGBA => 46;
use constant RBC_HSVA => 47;
use constant RBC_ALPHA => 48;
use constant RBC_OP_COUNT => 49;

@EXPORT = qw(RBC_ADD RBC_SUBTRACT RBC_MULT RBC_DIV RBC_MOD RBC_POW RBC_UMINUS RBC_MULTP RBC_ADDP RBC_SUBTRACTP RBC_SIN RBC_COS RBC_ATAN2 RBC_SQRT RBC_DISTANCE RBC_GETP1 RBC_GETP2 RBC_GETP3 RBC_VALUE RBC_HUE RBC_SAT RBC_HSV RBC_RED RBC_GREEN RBC_BLUE RBC_RGB RBC_INT RBC_IF RBC_IFP RBC_LE RBC_LT RBC_GE RBC_GT RBC_EQ RBC_NE RBC_AND RBC_OR RBC_NOT RBC_ABS RBC_RET RBC_JUMP RBC_JUMPZ RBC_JUMPNZ RBC_SET RBC_SETP RBC_PRINT RBC_RGBA RBC_HSVA RBC_ALPHA RBC_OP_COUNT);

%Attr = (
          'ne' => {
                    'opcode' => 34,
                    'types' => 'rr',
                    'func' => 0,
                    'parms' => 2,
                    'result' => 'r'
                  },
          'op_count' => {
                          'opcode' => 49,
                          'types' => '',
                          'func' => 0,
                          'parms' => 0,
                          'result' => undef
                        },
          'hsv' => {
                     'opcode' => 21,
                     'types' => 'rrr',
                     'func' => 1,
                     'parms' => 3,
                     'result' => 'p'
                   },
          'sqrt' => {
                      'opcode' => 13,
                      'types' => 'r',
                      'func' => 1,
                      'parms' => 1,
                      'result' => 'r'
                    },
          'atan2' => {
                       'opcode' => 12,
                       'types' => 'rr',
                       'func' => 1,
                       'parms' => 2,
                       'result' => 'r'
                     },
          'distance' => {
                          'opcode' => 14,
                          'types' => 'rrrr',
                          'func' => 1,
                          'parms' => 4,
                          'result' => 'r'
                        },
          'le' => {
                    'opcode' => 29,
                    'types' => 'rr',
                    'func' => 0,
                    'parms' => 2,
                    'result' => 'r'
                  },
          'not' => {
                     'opcode' => 37,
                     'types' => 'r',
                     'func' => 0,
                     'parms' => 1,
                     'result' => 'r'
                   },
          'print' => {
                       'opcode' => 45,
                       'types' => 'r',
                       'func' => 0,
                       'parms' => 1,
                       'result' => undef
                     },
          'if' => {
                    'opcode' => 27,
                    'types' => 'rrr',
                    'func' => 1,
                    'parms' => 3,
                    'result' => 'r'
                  },
          'green' => {
                       'opcode' => 23,
                       'types' => 'p',
                       'func' => 1,
                       'parms' => 1,
                       'result' => 'r'
                     },
          'or' => {
                    'opcode' => 36,
                    'types' => 'rr',
                    'func' => 0,
                    'parms' => 2,
                    'result' => 'r'
                  },
          'rgba' => {
                      'opcode' => 46,
                      'types' => 'rrrr',
                      'func' => 1,
                      'parms' => 4,
                      'result' => 'p'
                    },
          'red' => {
                     'opcode' => 22,
                     'types' => 'p',
                     'func' => 1,
                     'parms' => 1,
                     'result' => 'r'
                   },
          'addp' => {
                      'opcode' => 8,
                      'types' => 'pp',
                      'func' => 0,
                      'parms' => 2,
                      'result' => 'p'
                    },
          'eq' => {
                    'opcode' => 33,
                    'types' => 'rr',
                    'func' => 0,
                    'parms' => 2,
                    'result' => 'r'
                  },
          'value' => {
                       'opcode' => 18,
                       'types' => 'p',
                       'func' => 1,
                       'parms' => 1,
                       'result' => 'r'
                     },
          'jump' => {
                      'opcode' => 40,
                      'types' => '',
                      'func' => 0,
                      'parms' => 0,
                      'result' => undef
                    },
          'abs' => {
                     'opcode' => 38,
                     'types' => 'r',
                     'func' => 1,
                     'parms' => 1,
                     'result' => 'r'
                   },
          'sin' => {
                     'opcode' => 10,
                     'types' => 'r',
                     'func' => 1,
                     'parms' => 1,
                     'result' => 'r'
                   },
          'lt' => {
                    'opcode' => 30,
                    'types' => 'rr',
                    'func' => 0,
                    'parms' => 2,
                    'result' => 'r'
                  },
          'rgb' => {
                     'opcode' => 25,
                     'types' => 'rrr',
                     'func' => 1,
                     'parms' => 3,
                     'result' => 'p'
                   },
          'uminus' => {
                        'opcode' => 6,
                        'types' => 'r',
                        'func' => 0,
                        'parms' => 1,
                        'result' => 'r'
                      },
          'mult' => {
                      'opcode' => 2,
                      'types' => 'rr',
                      'func' => 0,
                      'parms' => 2,
                      'result' => 'r'
                    },
          'and' => {
                     'opcode' => 35,
                     'types' => 'rr',
                     'func' => 0,
                     'parms' => 2,
                     'result' => 'r'
                   },
          'ge' => {
                    'opcode' => 31,
                    'types' => 'rr',
                    'func' => 0,
                    'parms' => 2,
                    'result' => 'r'
                  },
          'div' => {
                     'opcode' => 3,
                     'types' => 'rr',
                     'func' => 0,
                     'parms' => 2,
                     'result' => 'r'
                   },
          'add' => {
                     'opcode' => 0,
                     'types' => 'rr',
                     'func' => 0,
                     'parms' => 2,
                     'result' => 'r'
                   },
          'int' => {
                     'opcode' => 26,
                     'types' => 'r',
                     'func' => 1,
                     'parms' => 1,
                     'result' => 'r'
                   },
          'jumpnz' => {
                        'opcode' => 42,
                        'types' => 'r',
                        'func' => 0,
                        'parms' => 1,
                        'result' => undef
                      },
          'cos' => {
                     'opcode' => 11,
                     'types' => 'r',
                     'func' => 1,
                     'parms' => 1,
                     'result' => 'r'
                   },
          'alpha' => {
                       'opcode' => 48,
                       'types' => 'p',
                       'func' => 1,
                       'parms' => 1,
                       'result' => 'r'
                     },
          'blue' => {
                      'opcode' => 24,
                      'types' => 'p',
                      'func' => 1,
                      'parms' => 1,
                      'result' => 'r'
                    },
          'set' => {
                     'opcode' => 43,
                     'types' => 'r',
                     'func' => 0,
                     'parms' => 1,
                     'result' => 'r'
                   },
          'jumpz' => {
                       'opcode' => 41,
                       'types' => 'r',
                       'func' => 0,
                       'parms' => 1,
                       'result' => undef
                     },
          'ret' => {
                     'opcode' => 39,
                     'types' => 'p',
                     'func' => 0,
                     'parms' => 1,
                     'result' => undef
                   },
          'hue' => {
                     'opcode' => 19,
                     'types' => 'p',
                     'func' => 1,
                     'parms' => 1,
                     'result' => 'r'
                   },
          'getp3' => {
                       'opcode' => 17,
                       'types' => 'rr',
                       'func' => 1,
                       'parms' => 2,
                       'result' => 'p'
                     },
          'getp2' => {
                       'opcode' => 16,
                       'types' => 'rr',
                       'func' => 1,
                       'parms' => 2,
                       'result' => 'p'
                     },
          'pow' => {
                     'opcode' => 5,
                     'types' => 'rr',
                     'func' => 0,
                     'parms' => 2,
                     'result' => 'r'
                   },
          'ifp' => {
                     'opcode' => 28,
                     'types' => 'rpp',
                     'func' => 1,
                     'parms' => 3,
                     'result' => 'p'
                   },
          'getp1' => {
                       'opcode' => 15,
                       'types' => 'rr',
                       'func' => 1,
                       'parms' => 2,
                       'result' => 'p'
                     },
          'setp' => {
                      'opcode' => 44,
                      'types' => 'p',
                      'func' => 0,
                      'parms' => 1,
                      'result' => 'p'
                    },
          'subtractp' => {
                           'opcode' => 9,
                           'types' => 'pp',
                           'func' => 0,
                           'parms' => 2,
                           'result' => 'p'
                         },
          'subtract' => {
                          'opcode' => 1,
                          'types' => 'rr',
                          'func' => 0,
                          'parms' => 2,
                          'result' => 'r'
                        },
          'gt' => {
                    'opcode' => 32,
                    'types' => 'rr',
                    'func' => 0,
                    'parms' => 2,
                    'result' => 'r'
                  },
          'sat' => {
                     'opcode' => 20,
                     'types' => 'p',
                     'func' => 1,
                     'parms' => 1,
                     'result' => 'r'
                   },
          'hsva' => {
                      'opcode' => 47,
                      'types' => 'rrrr',
                      'func' => 1,
                      'parms' => 4,
                      'result' => 'p'
                    },
          'multp' => {
                       'opcode' => 7,
                       'types' => 'pr',
                       'func' => 0,
                       'parms' => 2,
                       'result' => 'p'
                     },
          'mod' => {
                     'opcode' => 4,
                     'types' => 'rr',
                     'func' => 0,
                     'parms' => 2,
                     'result' => 'r'
                   }
        );
$MaxOperands = 4;
$PackCode = "i";
1;

__END__

=head1 NAME

Imager::Regops - generated information about the register based VM

=head1 SYNOPSIS

  use Imager::Regops;
  $Imager::Regops::Attr{$opname}->{opcode} # opcode for given operator
  $Imager::Regops::Attr{$opname}->{parms} # number of parameters
  $Imager::Regops::Attr{$opname}->{types} # types of parameters
  $Imager::Regops::Attr{$opname}->{func} # operator is a function
  $Imager::Regops::Attr{$opname}->{result} # r for numeric, p for pixel result
  $Imager::Regops::MaxOperands; # maximum number of operands

=head1 DESCRIPTION

This module is generated automatically from regmach.h so we don't need to 
maintain the same information in at least one extra place.

At least that's the idea.

=head1 AUTHOR

Tony Cook, tony@develop-help.com

=head1 SEE ALSO

perl(1), Imager(3), http://imager.perl.org/~addi/perl/Imager/

=cut

